apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    receivers:
    - name: slack-notification
      slack_configs:
      - channel: '####################'
        send_resolved: true
        title: |-
         [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
         {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
           {{" "}}(
           {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
           {{- end -}}
           )
         {{- end }}
        text: >-
         {{ range .Alerts -}}
         *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

         *Description:* {{ .Annotations.description }}

         *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
           {{ end }}
         {{ end }}
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: slack-notification
      repeat_interval: 3h
    templates:
    - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  creationTimestamp: "2023-08-23T14:57:28Z"
  labels:
    app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.25.0
    chart: prometheus-12.0.1
    component: alertmanager
    helm.sh/chart: alertmanager-0.33.1
    heritage: Helm
    release: prometheus
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
    manager: kubectl-create
    operation: Update
    time: "2023-08-23T14:57:28Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
    manager: helm
    operation: Update
    time: "2023-08-24T05:37:11Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:alertmanager.yml: {}
    manager: kubectl-edit
    operation: Update
    time: "2023-08-24T07:20:34Z"
  name: prometheus-alertmanager
  namespace: prometheus
  resourceVersion: "24726907"
  uid: 4319d761-f091-4208-8e4f-6e0416680771
